version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database_name
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3000:3000"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
